import { addDays, parseISO, todayISO } from "@/lib/date";
import type { AppState } from "@/types/domain";
import { defaultCategories } from "./tokens";

const sampleToday = todayISO();
const { year, month } = parseISO(sampleToday);

export const createInitialState = (): AppState => ({
  view: {
    tab: "home",
    year,
    month,
    selectedDate: sampleToday,
    dark: false,
    sheet: null,
    detailTaskId: null,
    detailHabitId: null,
  },
  categories: defaultCategories,
  tasks: [
    {
      id: "t_portfolio",
      title: "포트폴리오 정리",
      categoryId: "cat_me",
      startDate: addDays(sampleToday, -3),
      endDate: addDays(sampleToday, 2),
      priority: "medium",
      isCompleted: false,
      scheduledTime: null,
      tags: ["#작업"],
    },
    {
      id: "t_interview",
      title: "면접 준비 자료 정리",
      categoryId: "cat_me",
      startDate: sampleToday,
      endDate: addDays(sampleToday, 4),
      priority: "high",
      isCompleted: false,
      scheduledTime: "19:00",
      tags: ["#취업", "#면접"],
    },
    {
      id: "t_meeting",
      title: "업체 미팅",
      categoryId: "cat_ext",
      startDate: sampleToday,
      endDate: sampleToday,
      priority: "high",
      isCompleted: false,
      scheduledTime: "14:00",
      tags: ["#미팅"],
    },
    {
      id: "t_report",
      title: "팀 보고서 제출",
      categoryId: "cat_ext",
      startDate: addDays(sampleToday, -6),
      endDate: sampleToday,
      priority: "medium",
      isCompleted: false,
      scheduledTime: null,
      tags: [],
    },
    {
      id: "t_read",
      title: "독서 30분",
      categoryId: "cat_me",
      startDate: sampleToday,
      endDate: sampleToday,
      priority: "low",
      isCompleted: true,
      scheduledTime: null,
      tags: [],
    },
  ],
  habits: [
    {
      id: "h_run",
      title: "운동 30분",
      emoji: "🏃",
      category: "habit",
      startedAt: addDays(sampleToday, -12),
      recurType: "daily",
      log: Object.fromEntries(
        Array.from({ length: 9 }, (_, i) => [addDays(sampleToday, i - 8), 1]),
      ),
    },
    {
      id: "h_water",
      title: "물 2L",
      emoji: "💧",
      category: "habit",
      startedAt: addDays(sampleToday, -28),
      recurType: "daily",
      log: Object.fromEntries(
        Array.from({ length: 28 }, (_, i) => [addDays(sampleToday, i - 27), 1]),
      ),
    },
    {
      id: "h_stretch",
      title: "아침 스트레칭",
      emoji: "🧘",
      category: "habit",
      startedAt: addDays(sampleToday, -5),
      recurType: "weekly",
      recurDays: [1, 2, 3, 4, 5],
      log: {
        [addDays(sampleToday, -5)]: 1,
        [addDays(sampleToday, -4)]: 1,
        [addDays(sampleToday, -3)]: 1,
        [addDays(sampleToday, -1)]: 1,
      },
    },
  ],
  goals: [
    {
      id: "g_year_health",
      periodType: "yearly",
      periodKey: String(year),
      title: "체력 만들기",
      note: "주 3회 운동 루틴 정착",
      sortOrder: 0,
      locked: true,
      lockedAt: `${year}-01-01T00:00:00.000Z`,
    },
    {
      id: "g_year_career",
      periodType: "yearly",
      periodKey: String(year),
      title: "직무 전환 준비",
      note: "포트폴리오와 면접 루틴 만들기",
      sortOrder: 1,
      locked: true,
      lockedAt: `${year}-01-01T00:00:00.000Z`,
    },
    {
      id: "g_month_interview",
      periodType: "monthly",
      periodKey: `${year}-${String(month).padStart(2, "0")}`,
      title: "면접 준비 마무리",
      note: "자료 정리와 예상 질문 연습",
      sortOrder: 0,
      locked: true,
      lockedAt: `${year}-${String(month).padStart(2, "0")}-01T00:00:00.000Z`,
    },
    {
      id: "g_month_routine",
      periodType: "monthly",
      periodKey: `${year}-${String(month).padStart(2, "0")}`,
      title: "생활 리듬 회복",
      note: "운동과 물 마시기 유지",
      sortOrder: 1,
      locked: false,
      lockedAt: null,
    },
  ],
  goalPromptDismissals: [],
  settings: {
    notify: true,
    notifyTime: "09:00",
    weekStart: 0,
    plan: "free",
    justDoMode: false,
  },
});
